# =============================================================================
# Stage 1: Frontend build
# =============================================================================
FROM node:22-alpine AS frontend

WORKDIR /app

# Install shared dependencies first for better Docker layer reuse.
COPY frontend/shared/package.json /app/frontend/shared/package.json
RUN cd /app/frontend/shared && npm install

COPY frontend/admin/package.json /app/frontend/admin/package.json
RUN cd /app/frontend/admin && npm install

COPY frontend/user/package.json /app/frontend/user/package.json
RUN cd /app/frontend/user && npm install

# Copy full frontend source, including temporary .env.production.local files
# generated by scripts/build.sh with public VITE_* values only.
COPY frontend/shared/ /app/frontend/shared/
COPY frontend/admin/ /app/frontend/admin/
COPY frontend/user/ /app/frontend/user/

RUN mkdir -p /app/public/admin /app/public/user

RUN cd /app/frontend/admin && npm run build
RUN cd /app/frontend/user && npm run build

# =============================================================================
# Stage 2: Backend build
# =============================================================================
FROM rust:1-bookworm AS backend

ARG BINARY_NAME=app

WORKDIR /build/app

COPY . /build/app/
COPY --from=frontend /app/public/ /build/app/public/

RUN cargo build --release
RUN cargo run --release -- docs:api

# =============================================================================
# Stage 3: Artifact collection
# =============================================================================
FROM debian:bookworm-slim AS artifact

ARG BINARY_NAME=app

COPY --from=backend /build/app/target/release/${BINARY_NAME} /artifact/${BINARY_NAME}
COPY --from=backend /build/app/public/ /artifact/public/
COPY --from=backend /build/app/config/ /artifact/config/
COPY --from=backend /build/app/locales/ /artifact/locales/
COPY --from=backend /build/app/templates/ /artifact/templates/
COPY --from=backend /build/app/docs/api/ /artifact/docs/api/

CMD ["echo", "Build artifact ready"]
